In [1]:
import json

with open('/Users/petebrown/Developer/data-updater-v2/bbc-json/lineups/2020-01-01.json') as f:
    data = json.load(f)

In [2]:
data.keys()

dict_keys(['homeTeam', 'awayTeam', 'useCatalogue', 'officials'])

In [16]:
teams = ['homeTeam', 'awayTeam']

In [17]:
data['homeTeam'].keys()

dict_keys(['id', 'urn', 'name', 'alignment', 'formation', 'manager', 'players'])

In [18]:
data['homeTeam']['players'].keys()

dict_keys(['starters', 'substitutes'])

In [20]:
import pandas as pd

starters = data['homeTeam']['players']['starters']

starters_df = []

for s in starters:
    starters_df.append(pd.DataFrame.from_dict(s, orient='index').T)
starters_df = pd.concat(starters_df, ignore_index=True)

starter_names = pd.json_normalize(starters_df['name'])

pd.concat([starters_df, starter_names], axis=1)

,urn,name,position,shirtNumber,formationPlace,isCaptain,cards,displayName,substitutes,card,substitutedOff,short,first,last
0,urn:bbc:sportsdata:football:player:s-c9vek5ubp...,"{'short': 'A. Chapman', 'first': 'Aaron James'...",Goalkeeper,31,1,False,[],A. Chapman,[],NaN,NaN,A. Chapman,Aaron James,Chapman
1,urn:bbc:sportsdata:football:player:s-1a8msufvk...,"{'short': 'C. Woods', 'first': 'Calum Jack', '...",Defender,2,4,False,[],C. Woods,[],NaN,NaN,C. Woods,Calum Jack,Woods
2,urn:bbc:sportsdata:football:player:s-eabj99pro...,"{'short': 'G. Ray', 'first': 'George Edward', ...",Defender,5,5,False,[],G. Ray,[],NaN,NaN,G. Ray,George Edward,Ray
3,urn:bbc:sportsdata:football:player:s-2uwn00y18...,"{'short': 'S. Nelson', 'first': 'Sidney Raymon...",Defender,4,6,False,[],S. Nelson,[],NaN,NaN,S. Nelson,Sidney Raymond Kenneth,Nelson
4,urn:bbc:sportsdata:football:player:s-3gffyf2cg...,"{'short': 'K. Morris', 'first': 'Kieron', 'las...",Midfielder,7,3,False,"[{'type': 'Yellow Card', 'timeLabel': {'value'...",K. Morris,[],"{'type': {'value': 'yellow', 'accessibleValue'...",NaN,K. Morris,Kieron,Morris
5,urn:bbc:sportsdata:football:player:s-cc1ub1b70...,"{'short': 'D. Perkins', 'first': 'David Philip...",Midfielder,17,8,False,[],D. Perkins,[],NaN,NaN,D. Perkins,David Philip,Perkins
6,urn:bbc:sportsdata:football:player:s-dcu4iqh29...,"{'short': 'N. Danns', 'first': 'Neil Alexander...",Midfielder,35,7,False,[],N. Danns,[],NaN,NaN,N. Danns,Neil Alexander,Danns
7,urn:bbc:sportsdata:football:player:s-7qnu4sb2a...,"{'short': 'J. Caprice', 'first': 'Jake Lenox',...",Midfielder,14,2,False,[],J. Caprice,[],NaN,NaN,J. Caprice,Jake Lenox,Caprice
8,urn:bbc:sportsdata:football:player:s-7xr6yeu0y...,"{'short': 'C. Jennings', 'first': 'Connor Jose...",Attacking Midfielder,11,9,False,[],C. Jennings,[],NaN,NaN,C. Jennings,Connor Joseph,Jennings
9,urn:bbc:sportsdata:football:player:s-1uer7zbsj...,"{'short': 'M. Ferrier', 'first': 'Morgan James...",Striker,10,11,False,[],M. Ferrier,[],NaN,NaN,M. Ferrier,Morgan James,Ferrier
10,urn:bbc:sportsdata:football:player:s-4qrvri86m...,"{'short': 'C. Blackett-Taylor', 'first': 'Core...",Striker,23,10,False,[],C. Blackett-Taylor,[{'playerSubbedOutId': 'urn:bbc:sportsdata:foo...,NaN,"{'periodId': 2, 'timeMin': 70, 'timeMinSec': '...",C. Blackett-Taylor,Corey Josiah Paul,Blackett-Taylor

In [51]:
cards = starters_df.cards

for c in cards:
    if c:
        print(pd.json_normalize(c))
    

pd.json_normalize(cards)

          type timeLabel.value timeLabel.accessible
0  Yellow Card             24'           24 minutes

                                                    0
0                                                None
1                                                None
2                                                None
3                                                None
4   {'type': 'Yellow Card', 'timeLabel.value': '24...
5                                                None
6                                                None
7                                                None
8                                                None
9                                                None
10                                               None

In [52]:
subs = starters_df.substitutes

for s in subs:
    if s:
        print(pd.json_normalize(s))

                                   playerSubbedOutId  \
0  urn:bbc:sportsdata:football:player:s-4qrvri86m...

                                    playerSubbedInId playerSubbedInName  \
0  urn:bbc:sportsdata:football:player:s-dedo3aeuf...          P. Mullin

  timeLabel.value timeLabel.accessible
0             70'           70 minutes

In [49]:
subbed_off = starters_df.substitutedOff

pd.json_normalize(subbed_off)

,periodId,timeMin,timeMinSec,timestamp,playerOnUrn,playerOnName,reason
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2.0,70.0,69:32,2020-01-01T16:28:00Z,urn:bbc:sportsdata:football:player:s-dedo3aeuf...,P. Mullin,Tactical

In [15]:
import pandas as pd

pd.json_normalize(p)

,urn,position,shirtNumber,formationPlace,isCaptain,cards,displayName,substitutes,name.short,name.first,name.last
0,urn:bbc:sportsdata:football:player:s-c9vek5ubp...,Goalkeeper,31,1,False,[],A. Chapman,[],A. Chapman,Aaron James,Chapman

In [17]:
s = []

for starter in data['homeTeam']['players']['starters']:
    s.append(pd.json_normalize(starter))

In [23]:
s[4]

,urn,position,shirtNumber,formationPlace,isCaptain,cards,displayName,substitutes,name.short,name.first,name.last,card.type.value,card.type.accessibleValue,card.time.value,card.time.accessibleValue
0,urn:bbc:sportsdata:football:player:s-3gffyf2cg...,Midfielder,7,3,False,"[{'type': 'Yellow Card', 'timeLabel': {'value'...",K. Morris,[],K. Morris,Kieron,Morris,yellow,Yellow Card,24',24 minutes